kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sarcasm-workbench
  namespace: sarcasm-detection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  volumeMode: Filesystem